'use client';

import { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import AdminLayout from '@/components/admin/AdminLayout';
import api from '@/lib/api';

export default function ReportDetailPage() {
  const params = useParams();
  const router = useRouter();
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    fetchReport();
  }, []);

  const fetchReport = async () => {
    try {
      setLoading(true);
      const response = await api.get(`/compliance/reports/${params.id}`);
      setReport(response.data.data);
    } catch (error: any) {
      console.error('Error fetching report:', error);
      setError(error.response?.data?.message || 'Failed to load report');
    } finally {
      setLoading(false);
    }
  };

  const exportCSV = async () => {
    try {
      setExporting(true);
      const response = await api.get(`/compliance/reports/${params.id}/export-csv`, {
        responseType: 'blob'
      });
      
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `${report.report_name}.csv`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error exporting CSV:', error);
      alert('Failed to export CSV');
    } finally {
      setExporting(false);
    }
  };

  const getReportTypeLabel = (type: string) => {
    switch (type) {
      case 'DAILY_SUMMARY': return 'Daily Transaction Summary';
      case 'KYC_COMPLIANCE': return 'KYC Compliance Report';
      case 'FRAUD_DETECTION': return 'Fraud Detection Report';
      case 'AML_ALERTS': return 'AML Alerts Report';
      default: return type;
    }
  };

  if (loading) {
    return (
      <AdminLayout>
        <div className="flex items-center justify-center h-64">
          <div className="text-gray-500">Loading report...</div>
        </div>
      </AdminLayout>
    );
  }

  if (error || !report) {
    return (
      <AdminLayout>
        <div className="flex flex-col items-center justify-center h-64">
          <div className="text-red-500 mb-4">{error || 'Report not found'}</div>
          <button
            onClick={() => router.push('/admin/compliance/reports')}
            className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
          >
            Back to Reports
          </button>
        </div>
      </AdminLayout>
    );
  }

  return (
    <AdminLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-bold text-gray-900 dark:text-white">
              {report.report_name}
            </h1>
            <p className="text-gray-600 dark:text-gray-400 mt-1">
              {getReportTypeLabel(report.report_type)}
            </p>
          </div>
          <div className="flex gap-2">
            <button
              onClick={exportCSV}
              disabled={exporting}
              className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {exporting ? 'Exporting...' : 'Export CSV'}
            </button>
            <button
              onClick={() => router.push('/admin/compliance/reports')}
              className="px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700"
            >
              Back to Reports
            </button>
          </div>
        </div>

        {/* Report Metadata */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">Report Information</h2>
          <dl className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <dt className="text-sm text-gray-500 dark:text-gray-400">Report Type</dt>
              <dd className="mt-1 text-sm font-medium text-gray-900 dark:text-white">
                {getReportTypeLabel(report.report_type)}
              </dd>
            </div>
            <div>
              <dt className="text-sm text-gray-500 dark:text-gray-400">Generated By</dt>
              <dd className="mt-1 text-sm font-medium text-gray-900 dark:text-white">
                {report.generated_by_name || 'N/A'}
              </dd>
            </div>
            <div>
              <dt className="text-sm text-gray-500 dark:text-gray-400">Period</dt>
              <dd className="mt-1 text-sm font-medium text-gray-900 dark:text-white">
                <span className="en-digits">{new Date(report.date_from).toLocaleDateString('en-GB')} - {new Date(report.date_to).toLocaleDateString('en-GB')}</span>
              </dd>
            </div>
            <div>
              <dt className="text-sm text-gray-500 dark:text-gray-400">Generated At</dt>
              <dd className="mt-1 text-sm font-medium text-gray-900 dark:text-white">
                <span className="en-digits">{new Date(report.created_at).toLocaleDateString('en-GB')} {new Date(report.created_at).toLocaleTimeString('en-GB', { hour12: false })}</span>
              </dd>
            </div>
          </dl>
        </div>

        {/* Report Data */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">Report Data</h2>
          
          {/* Summary View for Different Report Types */}
          {report.report_data && (
            <div className="space-y-4">
              {/* Daily Summary */}
              {report.report_data.summary && (
                <div>
                  <h3 className="text-md font-medium text-gray-900 dark:text-white mb-2">Transaction Summary</h3>
                  <div className="overflow-x-auto">
                    <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                      <thead className="bg-gray-50 dark:bg-gray-700">
                        <tr>
                          <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-300">Status</th>
                          <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-300">Count</th>
                          <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-300">Total Amount</th>
                          <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-300">Avg Amount</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
                        {report.report_data.summary.map((row: any, idx: number) => (
                          <tr key={idx}>
                            <td className="px-4 py-2 text-sm text-gray-900 dark:text-white">{row.status}</td>
                            <td className="px-4 py-2 text-sm text-gray-900 dark:text-white">{row.count}</td>
                            <td className="px-4 py-2 text-sm text-gray-900 dark:text-white">${Number(row.total_amount || 0).toFixed(2)}</td>
                            <td className="px-4 py-2 text-sm text-gray-900 dark:text-white">${Number(row.avg_amount || 0).toFixed(2)}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}

              {/* KYC Statistics */}
              {report.report_data.statistics && (
                <div>
                  <h3 className="text-md font-medium text-gray-900 dark:text-white mb-2">KYC Statistics</h3>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    {report.report_data.statistics.map((stat: any, idx: number) => (
                      <div key={idx} className="bg-gray-50 dark:bg-gray-700 rounded-lg p-4">
                        <div className="text-sm text-gray-500 dark:text-gray-400">{stat.kyc_status}</div>
                        <div className="text-2xl font-bold text-gray-900 dark:text-white mt-1">{stat.count}</div>
                      </div>
                    ))}
                  </div>
                  {report.report_data.averageReviewTime && (
                    <div className="mt-4 text-sm text-gray-600 dark:text-gray-400">
                      Average Review Time: {Number(report.report_data.averageReviewTime).toFixed(2)} hours
                    </div>
                  )}
                </div>
              )}

              {/* Fraud Matches */}
              {report.report_data.matchesByType && (
                <div>
                  <h3 className="text-md font-medium text-gray-900 dark:text-white mb-2">Fraud Matches by Type</h3>
                  <div className="overflow-x-auto">
                    <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                      <thead className="bg-gray-50 dark:bg-gray-700">
                        <tr>
                          <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-300">Match Type</th>
                          <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-300">Count</th>
                          <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-300">Total Score</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
                        {report.report_data.matchesByType.map((row: any, idx: number) => (
                          <tr key={idx}>
                            <td className="px-4 py-2 text-sm text-gray-900 dark:text-white">{row.match_type}</td>
                            <td className="px-4 py-2 text-sm text-gray-900 dark:text-white">{row.count}</td>
                            <td className="px-4 py-2 text-sm text-gray-900 dark:text-white">{row.total_score || 0}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}

              {/* AML Alerts */}
              {report.report_data.alertsByType && (
                <div>
                  <h3 className="text-md font-medium text-gray-900 dark:text-white mb-2">AML Alerts by Type</h3>
                  <div className="overflow-x-auto">
                    <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                      <thead className="bg-gray-50 dark:bg-gray-700">
                        <tr>
                          <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-300">Type</th>
                          <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-300">Severity</th>
                          <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-300">Count</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
                        {report.report_data.alertsByType.map((row: any, idx: number) => (
                          <tr key={idx}>
                            <td className="px-4 py-2 text-sm text-gray-900 dark:text-white">{row.type}</td>
                            <td className="px-4 py-2 text-sm text-gray-900 dark:text-white">{row.severity}</td>
                            <td className="px-4 py-2 text-sm text-gray-900 dark:text-white">{row.count}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}

              {/* Raw JSON View */}
              <details className="mt-6">
                <summary className="cursor-pointer text-sm font-medium text-gray-700 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white">
                  View Raw JSON Data
                </summary>
                <pre className="mt-2 bg-gray-100 dark:bg-gray-900 p-4 rounded overflow-auto max-h-96 text-xs">
                  {JSON.stringify(report.report_data, null, 2)}
                </pre>
              </details>
            </div>
          )}
        </div>
      </div>
    </AdminLayout>
  );
}
